config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'top/index'

  resources :users
  resources :tag_product_maps
  resources :products
  resources :tags
  resources :sites


  get    '/welcome', to: "sessions#new",     as: :welcome
  post   '/login',   to: "sessions#create",  as: :login
  delete '/logout', to:  "sessions#destroy", as: :logout

  resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'top#index' 
end

app/models/tag_product_map.rb
class TagProductMap < ApplicationRecord
  belongs_to :tag
  belongs_to :product
end

app/controllers/tag_product_maps_controller.rb
class TagProductMapsController < ApplicationController
  before_action :set_tag_product_map, only: [:show, :edit, :update, :destroy]

  # GET /tag_product_maps
  # GET /tag_product_maps.json
  def index
    @tag_product_maps = TagProductMap.all
  end

  # GET /tag_product_maps/1
  # GET /tag_product_maps/1.json
  def show
  end

  # GET /tag_product_maps/new
  def new
    @tag_product_map = TagProductMap.new
  end

  # GET /tag_product_maps/1/edit
  def edit
  end

  # POST /tag_product_maps
  # POST /tag_product_maps.json
  def create
    @tag_product_map = TagProductMap.new(tag_product_map_params)

    respond_to do |format|
      if @tag_product_map.save
        format.html { redirect_to @tag_product_map, notice: 'Tag product map was successfully created.' }
        format.json { render :show, status: :created, location: @tag_product_map }
      else
        format.html { render :new }
        format.json { render json: @tag_product_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tag_product_maps/1
  # PATCH/PUT /tag_product_maps/1.json
  def update
    respond_to do |format|
      if @tag_product_map.update(tag_product_map_params)
        format.html { redirect_to @tag_product_map, notice: 'Tag product map was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag_product_map }
      else
        format.html { render :edit }
        format.json { render json: @tag_product_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_product_maps/1
  # DELETE /tag_product_maps/1.json
  def destroy
    @tag_product_map.destroy
    respond_to do |format|
      format.html { redirect_to tag_product_maps_url, notice: 'Tag product map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag_product_map
      @tag_product_map = TagProductMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_product_map_params
      params.require(:tag_product_map).permit(:tag_id, :product_id)
    end
end

app/helpers/tag_product_maps_helper.rb
module TagProductMapsHelper
end

app/views/tag_product_maps/_form.html.erb
<%= form_with(model: tag_product_map, local: true) do |form| %>
  <% if tag_product_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag_product_map.errors.count, "error") %> prohibited this tag_product_map from being saved:</h2>

      <ul>
      <% tag_product_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.text_field :tag_id, id: :tag_product_map_tag_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :tag_product_map_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tag_product_maps/edit.html.erb
<h1>Editing Tag Product Map</h1>

<%= render 'form', tag_product_map: @tag_product_map %>

<%= link_to 'Show', @tag_product_map %> |
<%= link_to 'Back', tag_product_maps_path %>

app/views/tag_product_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tag Product Maps</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_product_maps.each do |tag_product_map| %>
      <tr>
        <td><%= tag_product_map.tag %></td>
        <td><%= tag_product_map.product %></td>
        <td><%= link_to 'Show', tag_product_map %></td>
        <td><%= link_to 'Edit', edit_tag_product_map_path(tag_product_map) %></td>
        <td><%= link_to 'Destroy', tag_product_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag Product Map', new_tag_product_map_path %>

app/views/tag_product_maps/new.html.erb
<h1>New Tag Product Map</h1>

<%= render 'form', tag_product_map: @tag_product_map %>

<%= link_to 'Back', tag_product_maps_path %>

app/views/tag_product_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @tag_product_map.tag %>
</p>

<p>
  <strong>Product:</strong>
  <%= @tag_product_map.product %>
</p>

<%= link_to 'Edit', edit_tag_product_map_path(@tag_product_map) %> |
<%= link_to 'Back', tag_product_maps_path %>